ScottishConstituencies/config/routes.rb
Rails.application.routes.draw do
  get 'map/index'
  resources :results
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'results/index'
  root "results#index"
end

ScottishConstituencies/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ScottishConstituencies/app/models/result.rb
class Result < ApplicationRecord
end

ScottishConstituencies/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ScottishConstituencies/app/controllers/map_controller.rb
require 'json'
class MapController < ApplicationController
  def index
    
     @results = Result.all
    
  
  end
end

ScottishConstituencies/app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
    @results = Result.all
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def result_params
      params.require(:result).permit(:ons_code, :constituency, :region, :election_date, :electorate, :total_ballot, :total_valid, :rejected_ballot, :turnout, :rejected_ballot_percent, :con, :lab, :lib, :snp, :ind, :tusc, :grn, :other, :con_percent, :lab_percent, :lib_percent, :snp_percent, :ind_percent, :tusc_percent, :grn_percent, :other_percent, :win, :second)
    end
end

ScottishConstituencies/app/helpers/application_helper.rb
module ApplicationHelper
end

ScottishConstituencies/app/helpers/map_helper.rb
module MapHelper
end

ScottishConstituencies/app/helpers/results_helper.rb
module ResultsHelper
end

ScottishConstituencies/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScottishConstituencies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ScottishConstituencies/app/views/map/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      #mapDiv {
        width: 1200px;
        height: 800px;
      }
    </style>
  </head>
  <body>

    <h1>Scottish Constituencies</h1>
     
    <div id="mapDiv"></div>

<%= raw @jsonresults %>

  <script type="text/javascript">

var map;
function initMap() {
  map = new google.maps.Map(document.getElementById('mapDiv'), {
    //zoom: 8,
    //center: {lat: 57.477772, lng: -4.224721}  //centering on Edinburgh
  });
  

var json = <%= raw @results.to_json %>



function getResultsID(constituencyID){
  for(var i = 0; i < json.length; i++) {
    var obj = json[i];
      if (obj.ons_code == constituencyID){
        return obj.id
      }
  }
}

function getWinnerColour(constituencyID){
  for(var i = 0; i < json.length; i++) {
    var obj = json[i];
    if (obj.ons_code == constituencyID){
      switch(obj.win) {
         case "SNP":
           return "yellow"
           break;
         case "Con":
           return "blue"
           break;
         case "LD":
           return "orange"
           break;
         case "Lab":
           return "red"
           break;
           
         default:
           return "white"
      }
    }
  }
  
}

  map.data.loadGeoJson('/Scottish_Parliamentary_Constituencies_May_2016_Generalised_Clipped_Boundaries_in_Scotland.json');
  
   
   
  var bounds = new google.maps.LatLngBounds();
  
  setTimeout(function() {
  map.data.forEach(function(feature){
    
    if(feature.getGeometry().getType() === 'Polygon'){
      feature.getGeometry().forEachLatLng(function(latlng){
        bounds.extend(latlng);
      });
      
    } 
    
  });
    map.fitBounds(bounds);
  map.setCenter(bounds.getCenter());
  }, 500); 
  
  
  
  
  map.data.setStyle(function(feature) {
    
    //alert(json)
    var constituencyID = feature.getProperty('spc16cd');
    var winnerColour =  getWinnerColour(constituencyID);
    //alert(winnerColour)
    return{
      fillColor: winnerColour,
      strokeWeight: 1
      }

  });
  
  map.data.addListener('click', function(event) {
   //map.data.overrideStyle(event.feature, {fillColor: 'red'});
   //window.location.href = "http://www.google.co.uk";
   var constituencyID = event.feature.getProperty('spc16cd');
   //var shape = "";
   //event.feature.getGeometry().forEachLatLng(function(latlng){
        //shape += latlng
   // });
   var resultsID = getResultsID(constituencyID);
   var constituencyID = event.feature.getProperty('spc16cd');
   

   //alert("/results/" + resultsID);
   window.location.href = "/results/" + resultsID;
   
  });
  
  
}
    
   </script>

    <script
      async
      defer
      src="<your key>">
    </script>
  </body>
</html>

ScottishConstituencies/app/views/results/_form.html.erb
<%= form_with(model: result, local: true) do |form| %>
  <% if result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
        <% result.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ons_code %>
    <%= form.text_field :ons_code %>
  </div>

  <div class="field">
    <%= form.label :constituency %>
    <%= form.text_field :constituency %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field">
    <%= form.label :election_date %>
    <%= form.date_select :election_date %>
  </div>

  <div class="field">
    <%= form.label :electorate %>
    <%= form.number_field :electorate %>
  </div>

  <div class="field">
    <%= form.label :total_ballot %>
    <%= form.number_field :total_ballot %>
  </div>

  <div class="field">
    <%= form.label :total_valid %>
    <%= form.number_field :total_valid %>
  </div>

  <div class="field">
    <%= form.label :rejected_ballot %>
    <%= form.number_field :rejected_ballot %>
  </div>

  <div class="field">
    <%= form.label :turnout %>
    <%= form.text_field :turnout %>
  </div>

  <div class="field">
    <%= form.label :rejected_ballot_percent %>
    <%= form.text_field :rejected_ballot_percent %>
  </div>

  <div class="field">
    <%= form.label :con %>
    <%= form.number_field :con %>
  </div>

  <div class="field">
    <%= form.label :lab %>
    <%= form.number_field :lab %>
  </div>

  <div class="field">
    <%= form.label :lib %>
    <%= form.number_field :lib %>
  </div>

  <div class="field">
    <%= form.label :snp %>
    <%= form.number_field :snp %>
  </div>

  <div class="field">
    <%= form.label :ind %>
    <%= form.number_field :ind %>
  </div>

  <div class="field">
    <%= form.label :tusc %>
    <%= form.number_field :tusc %>
  </div>

  <div class="field">
    <%= form.label :grn %>
    <%= form.number_field :grn %>
  </div>

  <div class="field">
    <%= form.label :other %>
    <%= form.number_field :other %>
  </div>

  <div class="field">
    <%= form.label :con_percent %>
    <%= form.text_field :con_percent %>
  </div>

  <div class="field">
    <%= form.label :lab_percent %>
    <%= form.text_field :lab_percent %>
  </div>

  <div class="field">
    <%= form.label :lib_percent %>
    <%= form.text_field :lib_percent %>
  </div>

  <div class="field">
    <%= form.label :snp_percent %>
    <%= form.text_field :snp_percent %>
  </div>

  <div class="field">
    <%= form.label :ind_percent %>
    <%= form.text_field :ind_percent %>
  </div>

  <div class="field">
    <%= form.label :tusc_percent %>
    <%= form.text_field :tusc_percent %>
  </div>

  <div class="field">
    <%= form.label :grn_percent %>
    <%= form.text_field :grn_percent %>
  </div>

  <div class="field">
    <%= form.label :other_percent %>
    <%= form.text_field :other_percent %>
  </div>

  <div class="field">
    <%= form.label :win %>
    <%= form.text_field :win %>
  </div>

  <div class="field">
    <%= form.label :second %>
    <%= form.text_field :second %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ScottishConstituencies/app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

ScottishConstituencies/app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Results</h1>

<table>
  <thead>
    <tr>
      <th>Ons code</th>
      <th>Constituency</th>
      <th>Region</th>
      <th>Election date</th>
      <th>Electorate</th>
      <th>Total ballot</th>
      <th>Total valid</th>
      <th>Rejected ballot</th>
      <th>Turnout</th>
      <th>Rejected ballot percent</th>
      <th>Con</th>
      <th>Lab</th>
      <th>Lib</th>
      <th>Snp</th>
      <th>Ind</th>
      <th>Tusc</th>
      <th>Grn</th>
      <th>Other</th>
      <th>Con percent</th>
      <th>Lab percent</th>
      <th>Lib percent</th>
      <th>Snp percent</th>
      <th>Ind percent</th>
      <th>Tusc percent</th>
      <th>Grn percent</th>
      <th>Other percent</th>
      <th>Win</th>
      <th>Second</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.ons_code %></td>
        <td><%= result.constituency %></td>
        <td><%= result.region %></td>
        <td><%= result.election_date %></td>
        <td><%= result.electorate %></td>
        <td><%= result.total_ballot %></td>
        <td><%= result.total_valid %></td>
        <td><%= result.rejected_ballot %></td>
        <td><%= result.turnout %></td>
        <td><%= result.rejected_ballot_percent %></td>
        <td><%= result.con %></td>
        <td><%= result.lab %></td>
        <td><%= result.lib %></td>
        <td><%= result.snp %></td>
        <td><%= result.ind %></td>
        <td><%= result.tusc %></td>
        <td><%= result.grn %></td>
        <td><%= result.other %></td>
        <td><%= result.con_percent %></td>
        <td><%= result.lab_percent %></td>
        <td><%= result.lib_percent %></td>
        <td><%= result.snp_percent %></td>
        <td><%= result.ind_percent %></td>
        <td><%= result.tusc_percent %></td>
        <td><%= result.grn_percent %></td>
        <td><%= result.other_percent %></td>
        <td><%= result.win %></td>
        <td><%= result.second %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

ScottishConstituencies/app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form', result: @result %>

<%= link_to 'Back', results_path %>

ScottishConstituencies/app/views/results/show.html.erb
<style type="text/css">
      #mapDiv {
        width: 600px;
        height: 400px;
      }
    </style>
    
    <div id="mapDiv"></div>
<p>
  <strong>Ons code:</strong>
  <%= @result.ons_code %>
</p>

<p>
  <strong>Constituency:</strong>
  <%= @result.constituency %>
</p>

<p>
  <strong>Region:</strong>
  <%= @result.region %>
</p>

<p>
  <strong>Election date:</strong>
  <%= @result.election_date %>
</p>

<p>
  <strong>Electorate:</strong>
  <%= @result.electorate %>
</p>

<p>
  <strong>Total ballot:</strong>
  <%= @result.total_ballot %>
</p>

<p>
  <strong>Total valid:</strong>
  <%= @result.total_valid %>
</p>

<p>
  <strong>Rejected ballot:</strong>
  <%= @result.rejected_ballot %>
</p>

<p>
  <strong>Turnout:</strong>
  <%= @result.turnout %>
</p>

<p>
  <strong>Rejected ballot percent:</strong>
  <%= @result.rejected_ballot_percent %>
</p>

<p>
  <strong>Con:</strong>
  <%= @result.con %>
</p>

<p>
  <strong>Lab:</strong>
  <%= @result.lab %>
</p>

<p>
  <strong>Lib:</strong>
  <%= @result.lib %>
</p>

<p>
  <strong>Snp:</strong>
  <%= @result.snp %>
</p>

<p>
  <strong>Ind:</strong>
  <%= @result.ind %>
</p>

<p>
  <strong>Tusc:</strong>
  <%= @result.tusc %>
</p>

<p>
  <strong>Grn:</strong>
  <%= @result.grn %>
</p>

<p>
  <strong>Other:</strong>
  <%= @result.other %>
</p>

<p>
  <strong>Con percent:</strong>
  <%= @result.con_percent %>
</p>

<p>
  <strong>Lab percent:</strong>
  <%= @result.lab_percent %>
</p>

<p>
  <strong>Lib percent:</strong>
  <%= @result.lib_percent %>
</p>

<p>
  <strong>Snp percent:</strong>
  <%= @result.snp_percent %>
</p>

<p>
  <strong>Ind percent:</strong>
  <%= @result.ind_percent %>
</p>

<p>
  <strong>Tusc percent:</strong>
  <%= @result.tusc_percent %>
</p>

<p>
  <strong>Grn percent:</strong>
  <%= @result.grn_percent %>
</p>

<p>
  <strong>Other percent:</strong>
  <%= @result.other_percent %>
</p>

<p>
  <strong>Win:</strong>
  <%= @result.win %>
</p>

<p>
  <strong>Second:</strong>
  <%= @result.second %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>

<script>
var map;
function initMap() {
  map = new google.maps.Map(document.getElementById('mapDiv'), {
    zoom: 10,
   
  });
  

var json = <%= raw @results.to_json %>



function getResultsID(constituencyID){
  for(var i = 0; i < json.length; i++) {
    var obj = json[i];
      if (obj.ons_code == constituencyID){
        return obj.id
      }
  }
}

function getWinnerColour(constituencyID){
  for(var i = 0; i < json.length; i++) {
    var obj = json[i];
    if (obj.ons_code == constituencyID){
      switch(obj.win) {
         case "SNP":
           return "yellow"
           break;
         case "Con":
           return "blue"
           break;
         case "LD":
           return "orange"
           break;
         case "Lab":
           return "red"
           break;
           
         default:
           return "white"
      }
    }
  }
  
}

  map.data.loadGeoJson('/Scottish_Parliamentary_Constituencies_May_2016_Generalised_Clipped_Boundaries_in_Scotland.json');
  
   
   
  var bounds = new google.maps.LatLngBounds();
  
  setTimeout(function() {
  map.data.forEach(function(feature){
    
    if(feature.getProperty('spc16cd') === "<%= raw @result.ons_code %>"){
      feature.getGeometry().forEachLatLng(function(latlng){
        bounds.extend(latlng);
      });
      
    } 
    
  });
    map.fitBounds(bounds);
  //map.setCenter(bounds.getCenter());
  }, 500); 
  
  
  
  
  map.data.setStyle(function(feature) {
    
    //alert(json)
    var constituencyID = feature.getProperty('spc16cd');
    var winnerColour =  getWinnerColour(constituencyID);
    //alert(winnerColour)
    return{
      fillColor: winnerColour,
      strokeWeight: 1
      }

  });
  
  map.data.addListener('click', function(event) {
   //map.data.overrideStyle(event.feature, {fillColor: 'red'});
   //window.location.href = "http://www.google.co.uk";
   var constituencyID = event.feature.getProperty('spc16cd');
   //var shape = "";
   //event.feature.getGeometry().forEachLatLng(function(latlng){
        //shape += latlng
   // });
   var resultsID = getResultsID(constituencyID);
   var constituencyID = event.feature.getProperty('spc16cd');
   

   //alert("/results/" + resultsID);
   window.location.href = "/results/" + resultsID;
   
  });
  
  
} 
</script>

<script
      async
      defer
      src="<your key>">
</script>